### PR TITLE
Adding a new provider for Redis Cache

### PR DESCRIPTION
**Pull request by shibayan**
### Motivation

Asynchronous implementation of aspnet-redis-providers is fake.
https://github.com/Azure/aspnet-redis-providers

I needed an implementation using StackExchange.Redis's asynchronous method

### Details

Based on the implementation of CosmosDB Provider, Stored procedures replaced by Redis LuaScripting.
Please give me feedback if anything is missing. I will respond as soon as possible.

### CODE REVIEW

**Comment by Jinhuafei** [comment]
@shibayan , we will review the PR. 
@JonCole FYI

**Comment by JonCole** [comment]
@shibayan - The decision to have the provider at https://github.com/Azure/aspnet-redis-providers build upon the sync code paths in StackExchange.Redis was for for several reasons, including: 

1. testing showed that we got better performance from the sync code paths than from the async code paths.
2. the async code paths in SE.Redis did not, at the time, have support for timing out async calls
3. the sync code paths surface very good diagnostic information that is not available in the async code paths.  Having that information is critical for customers to be able to root cause common client-side issues.

Now, having said that, the StackExchange.Redis 2.0 version that was recently released has supposedly fixed items 2 and 3 above, but we have not yet tested that. 

Once we have validated that the async code paths are better than the sync code paths (or at least on par with them), then we would certainly be open to moving from sync to async.

**Comment by shibayan** [comment]
@JonCole 
Thanks. OK. I will check the performance.
And I also understood the reason why I avoided async, so I will consider that area. Thank you.

**Comment by Jinhuafei** [comment]
@shibayan I'm closing this PR. If you are interested in contributing to ASP.NET Redis Sessionstate Provider, you can send PR on its [github repo](https://github.com/Azure/aspnet-redis-providers).

**Pull request closed without merging**
