### PR TITLE
Fix NRE in InProc store

### LINKED ISSUE #94: InProc throws NRE in 2.0.0
Just noticed the new version dropped, I get an NRE in the 2.0.0 version due to this line, while using InProcess mode.

var skipKA = config["skipKeepAliveWhenUnused"];

Because `config` is null in the case of InProc.  Simple solution was to add null coalesce operator on the indexing.

### PR DESCRIPTION
**Pull request by duncansmart**
Fixes #94

### CODE REVIEW

**Comment by sharadshahihw** [comment]
Will this PR get merged?

**Comment by Myrtanim** [comment]
@StephenMolloy, @Jinhuafei any chance to get this PR merged in and released? I also need this and would like to get rid of the work-around mentioned in #94.

**Comment by Dhugal** [comment]
Bump...

**Comment by DSXplor** [comment]
We are getting this issue too, do we have a timeframe for when the fix will be released?

**Comment by rotem925** [comment]
Was this released? I hit the same issue with v2.0, afaik, 2.0 is still the latest. Almost a year when this was merged..

**Pull request merged**
